name: journals
channels:
  - bokeh
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3
  - flask
  - flask-wtf
  - numpy
  - pandas
  - pytest
  - pytest-cov
  - python-dotenv
  - requests
  - jupyterlab
  - jupyter_nbextensions_configurator
  - beautifulsoup4
  - bokeh
  - lxml
  - matplotlib
  - xlrd
  - fuzzywuzzy
  - networkx
  - beautifulsoup4
  - html5lib
  - xmltodict
  - tabulate
  - bibtexparser
  - seaborn
  - faker
  - line_profiler
  - yaml
  - gunicorn
  - sphinx
  - zeep
  - flask-markdown
  - openpyxl
  - pip:
      - iso4
      - RISparser
      - bootstrap-flask
      - dominate
      - visitor
      - Flask-Session
      - pytest-check
