name: jot
channels:
  - bokeh
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3
  - flask
  - flask-wtf
  - numpy
  - pandas
  - pytest
  - pytest-cov
  - python-dotenv
  - requests
  - beautifulsoup4
  - bokeh>=2.4.0
  - lxml>=4.6.5
  - matplotlib
  - xlrd
  - networkx
  - beautifulsoup4
  - html5lib
  - xmltodict
  - tabulate
  - bibtexparser
  - seaborn
  - faker
  - line_profiler
  - yaml
  - gunicorn
  - gevent
  - sphinx
  - zeep
  - flask-markdown
  - openpyxl
  - appdirs
  - rich
  - Flask-SQLAlchemy
  - pyxlsb
  - pip:
      - iso4
      - RISparser
      - bootstrap-flask>=2.0.1
      - dominate
      - visitor
      - Flask-Session
      - pytest-check
      - flask-migrate
      - Flask-Moment
